import { ArchaeologicalFind } from './types';
import { NEW_SWEDISH_FINDS } from './newSwedishFinds';

export const ARCHAEOLOGICAL_FINDS: ArchaeologicalFind[] = [
  // PALEOLITIKUM (äldre stenålder, ~2,6 miljoner–10 000 f.Kr.)
  {
    id: 'segebro',
    name: 'Segebro',
    nameEn: 'Segebro',
    lat: 55.70,
    lng: 13.17,
    period: 'paleolithic',
    culture: 'Brommekultur',
    significance: 'Den första säkra paleolitiska boplatsen i Sverige',
    description: 'Flintverktyg från renjägarläger från Brommekulturen. Grävdes ut av Bengt Salomonsson 1960.',
    startYear: -12000,
    endYear: -11000,
    country: 'Sweden',
    findType: 'settlement'
  },
  {
    id: 'mollerod',
    name: 'Mölleröd',
    nameEn: 'Mölleröd',
    lat: 56.0,
    lng: 13.5,
    period: 'paleolithic',
    culture: 'Senpalolitikum',
    significance: 'Flintaföremål från senpalolitikum',
    description: 'Zinken och flintverktyg hittade av Ingvar Jönsson 1990 vid Finjasjöns norra strand.',
    startYear: -12000,
    endYear: -10000,
    country: 'Sweden',
    findType: 'artifacts'
  },
  {
    id: 'neanderthal',
    name: 'Neanderdalen',
    nameEn: 'Neander Valley',
    lat: 51.23,
    lng: 6.94,
    period: 'paleolithic',
    culture: 'Neandertal',
    significance: 'Ett av historiens största arkeologiska fynd',
    description: 'Neandertalfossil, stenverktyg och brända benrester från 1856.',
    startYear: -42000,
    endYear: -40000,
    country: 'Germany',
    findType: 'human_remains'
  },
  {
    id: 'schoningen',
    name: 'Schöningen',
    nameEn: 'Schöningen',
    lat: 52.15,
    lng: 10.95,
    period: 'paleolithic',
    culture: 'Homo heidelbergensis',
    significance: 'Äldsta trävapnen i världen',
    description: 'Spjut tillverkade helt i trä för 400 000 år sedan.',
    startYear: -400000,
    endYear: -380000,
    country: 'Germany',
    findType: 'weapons'
  },

  // MESOLITIKUM (mellanstenålder, ~10 000–4 000 f.Kr.)
  {
    id: 'tybrind_vig',
    name: 'Tybrind Vig',
    nameEn: 'Tybrind Vig',
    lat: 55.45,
    lng: 9.77,
    period: 'mesolithic',
    culture: 'Erteböllekultur',
    significance: 'Den största undervandsutgrävningen i Nordeuropa',
    description: 'Tre stammebåde från Ertebøllekulturen, den bäst bevarade 10m lång.',
    startYear: -5400,
    endYear: -3900,
    country: 'Denmark',
    findType: 'boats'
  },
  {
    id: 'norje_sunnansund',
    name: 'Norje Sunnansund',
    nameEn: 'Norje Sunnansund',
    lat: 56.25,
    lng: 14.62,
    period: 'mesolithic',
    culture: 'Tidigmesolitikum',
    significance: 'Bevarade ben och trä från mesolitikum',
    description: 'Över 18000 benfragment och nästan 300 ben- och hornverktyg.',
    startYear: -9600,
    endYear: -6600,
    country: 'Sweden',
    findType: 'settlement'
  },
  {
    id: 'stora_forvar',
    name: 'Stora Förvar',
    nameEn: 'Stora Förvar',
    lat: 57.17,
    lng: 17.98,
    period: 'mesolithic',
    culture: 'Stenålder-medeltid',
    significance: 'Kontinuerlig mänsklig aktivitet genom årtusenden',
    description: '7000 fynd från 4 meter kulturlager, stenåldern till medeltiden.',
    startYear: -8000,
    endYear: 1400,
    country: 'Sweden',
    findType: 'cave'
  },
  {
    id: 'margreteberg',
    name: 'Margreteberg',
    nameEn: 'Margreteberg',
    lat: 58.32,
    lng: 12.60,
    period: 'mesolithic',
    culture: 'Lihultkultur',
    significance: 'Fyndrikaste boplatsen i Vänerregionen',
    description: 'Minst 10 000 artefakter, omfattande samlingar av lihultyxor.',
    startYear: -6000,
    endYear: -4000,
    country: 'Sweden',
    findType: 'settlement'
  },

  // NEOLITIKUM (yngre stenålder, ~4 000–1 800 f.Kr.)
  {
    id: 'almhov',
    name: 'Almhov',
    nameEn: 'Almhov',
    lat: 55.7,
    lng: 13.5,
    period: 'neolithic',
    culture: 'Tidigneolitikum',
    significance: 'Tidig boskapsskötsel med helårskalvning',
    description: 'Isotopstudier visar avancerad boskapsskötsel under neolitikum.',
    startYear: -4000,
    endYear: -3500,
    country: 'Sweden',
    findType: 'settlement'
  },
  {
    id: 'copper_axes_serbia',
    name: 'Kopparyxor från Serbien',
    nameEn: 'Serbian Copper Axes',
    lat: 55.6,
    lng: 13.0,
    period: 'neolithic',
    culture: 'Stenålder',
    significance: 'Fjärrhandel redan under stenåldern',
    description: 'Kopparyxor från Skåne med koppar från Serbien, 4100 f.Kr.',
    startYear: -4100,
    endYear: -3800,
    country: 'Sweden',
    findType: 'trade'
  },

  // BRONSÅLDERN (~1 800–500 f.Kr.)
  {
    id: 'rishammar',
    name: 'Rishammar',
    nameEn: 'Rishammar',
    lat: 57.87,
    lng: 11.98,
    period: 'bronze_age',
    culture: 'Äldre bronsålder',
    significance: 'Rik kvinnograv med söderländska traditioner',
    description: 'Kvinna begravd med stora bronssmycken och bronsdolk.',
    startYear: -1800,
    endYear: -1200,
    country: 'Sweden',
    findType: 'burial'
  },
  {
    id: 'sjobol',
    name: 'Sjöbol',
    nameEn: 'Sjöbol',
    lat: 58.3,
    lng: 11.7,
    period: 'bronze_age',
    culture: 'Bronsålder',
    significance: 'Skandinaviens största fynd av gjutavfall',
    description: 'Skickliga bronshantverkare för 3000 år sedan med ugnar och verkstäder.',
    startYear: -1200,
    endYear: -800,
    country: 'Sweden',
    findType: 'workshop'
  },

  // JÄRNÅLDERN (~500 f.Kr.–800 e.Kr.)
  {
    id: 'alken_enge',
    name: 'Alken Enge',
    nameEn: 'Alken Enge',
    lat: 56.0,
    lng: 9.8,
    period: 'iron_age',
    culture: 'Romersk järnålder',
    significance: 'Rituella krigsoffer',
    description: 'Flera hundra krigares kvarlevor från rituella offer strax efter Kristi födelse.',
    startYear: 1,
    endYear: 100,
    country: 'Denmark',
    findType: 'ritual'
  },
  {
    id: 'uppakra',
    name: 'Uppåkra',
    nameEn: 'Uppåkra',
    lat: 55.75,
    lng: 13.30,
    period: 'iron_age',
    culture: 'Romersk järnålder-vikingatid',
    significance: 'Skandinaviens största järnåldersstad',
    description: 'Spår av trädgårdsodling: dill, persilja, kål, rova, palsternacka, morot.',
    startYear: 100,
    endYear: 1000,
    country: 'Sweden',
    findType: 'city'
  },

  // FOLKVANDRINGSTIDEN (375–550 e.Kr.)
  {
    id: 'hogom',
    name: 'Högom',
    nameEn: 'Högom',
    lat: 62.39,
    lng: 17.31,
    period: 'migration_period',
    culture: 'Folkvandringstid',
    significance: 'Praktfull hövdingebegravning',
    description: 'Hövding begravd på björnfäll med svärd, guld och glasbägare från Svartahavsområdet.',
    startYear: 500,
    endYear: 550,
    country: 'Sweden',
    findType: 'burial'
  },

  // VENDELTIDEN (550–800 e.Kr.)
  {
    id: 'vendel',
    name: 'Vendel',
    nameEn: 'Vendel',
    lat: 59.88,
    lng: 17.61,
    period: 'vendel_period',
    culture: 'Vendeltid',
    significance: 'Namngivande fyndplats för vendeltiden',
    description: 'Båtgravar med praktfulla stridshjälmar, vapen och ridutrustning.',
    startYear: 600,
    endYear: 800,
    country: 'Sweden',
    findType: 'boat_graves'
  },
  {
    id: 'valsgarde',
    name: 'Valsgärde',
    nameEn: 'Valsgärde',
    lat: 59.87,
    lng: 17.60,
    period: 'vendel_period',
    culture: 'Vendeltid',
    significance: 'Båtgravar från vendeltid',
    description: 'Gravfält med båtgravar från 600-800 e.Kr.',
    startYear: 600,
    endYear: 800,
    country: 'Sweden',
    findType: 'boat_graves'
  },
  {
    id: 'gamla_uppsala',
    name: 'Gamla Uppsala',
    nameEn: 'Old Uppsala',
    lat: 59.89,
    lng: 17.63,
    period: 'vendel_period',
    culture: 'Vendeltid',
    significance: 'Kungliga gravar med praktföremål',
    description: 'Storhögar med kungliga fynd av guld och elfenben från 500-talet.',
    startYear: 500,
    endYear: 700,
    country: 'Sweden',
    findType: 'royal_burial'
  },
  {
    id: 'torslunda',
    name: 'Torslunda',
    nameEn: 'Torslunda',
    lat: 56.67,
    lng: 16.50,
    period: 'vendel_period',
    culture: 'Vendeltid',
    significance: 'Torslundaplåtarna',
    description: 'Bronsplåtar för pressning av tunt bronsbleck från gravhög.',
    startYear: 600,
    endYear: 800,
    country: 'Sweden',
    findType: 'metalwork'
  },
  {
    id: 'grobin',
    name: 'Grobin (Seeburg)',
    nameEn: 'Grobin (Seeburg)',
    lat: 56.53,
    lng: 21.40,
    period: 'vendel_period',
    culture: 'Vendeltid',
    significance: 'Handelsstation i Baltikum',
    description: 'Skandinavisk handelsstation grundad under vendeltiden.',
    startYear: 600,
    endYear: 800,
    country: 'Latvia',
    findType: 'trading_post'
  },
  {
    id: 'sutton_hoo',
    name: 'Sutton Hoo',
    nameEn: 'Sutton Hoo',
    lat: 52.09,
    lng: 1.34,
    period: 'vendel_period',
    culture: 'Anglosaxisk',
    significance: 'Praktfull båtgrav med skandinaviska likheter',
    description: 'Båtgrav från tidigt 600-tal med kulturkontakter till Skandinavien.',
    startYear: 600,
    endYear: 650,
    country: 'England',
    findType: 'boat_graves'
  },

  // VIKINGATIDEN (800–1050 e.Kr.)
  {
    id: 'birka',
    name: 'Birka',
    nameEn: 'Birka',
    lat: 59.33,
    lng: 17.54,
    period: 'viking_age',
    culture: 'Vikingatid',
    significance: 'En av vikingatidens viktigaste handelsstäder',
    description: 'Rika gravar och handelsföremål från hela världen.',
    startYear: 750,
    endYear: 970,
    country: 'Sweden',
    findType: 'trading_city'
  },
  {
    id: 'lindisfarne',
    name: 'Lindisfarne',
    nameEn: 'Lindisfarne',
    lat: 55.67,
    lng: -1.80,
    period: 'viking_age',
    culture: 'Vikingatid',
    significance: 'Första vikingaraiden 793 e.Kr.',
    description: 'Klosterplundring som markerade början av vikingatiden.',
    startYear: 793,
    endYear: 793,
    country: 'England',
    findType: 'raid'
  },
  {
    id: 'salme',
    name: 'Salme',
    nameEn: 'Salme',
    lat: 58.37,
    lng: 22.05,
    period: 'viking_age',
    culture: 'Vikingatid',
    significance: 'Båtgravar med krigare',
    description: 'Fyrtiotal män begravda i två båtar, vissa lemlästade.',
    startYear: 800,
    endYear: 900,
    country: 'Estonia',
    findType: 'boat_graves'
  },

  // Add the new Swedish finds
  ...NEW_SWEDISH_FINDS
];
