-- Add regional center coordinates for inscriptions without specific locations
-- Based on signum prefixes for regional placement

-- Öland inscriptions (Öl prefix) - Öland center: 56.7, 16.7
INSERT INTO additional_coordinates (signum, latitude, longitude, source, confidence, notes) VALUES
('Öl 1', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 2', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 3', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 4', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 5', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 6', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 7', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 8', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 9', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 10', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 11', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 12', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 13', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 14', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 15', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 16', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 17', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 18', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 19', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 20', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 21', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 22', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 23', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 24', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 25', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 26', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 27', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 28', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 29', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 30', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 31', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 32', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 33', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 34', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 35', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 36', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 37', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 38', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 39', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 40', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 41', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 42', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 43', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 44', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 45', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 46', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 47', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 48', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 49', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center'),
('Öl 50', 56.7, 16.7, 'regional_center', 'medium', 'Öland regional center');