-- Lägg till U 489 (Laggastenen) - känd för brobyggnad och Öpirs signatur
INSERT INTO runic_inscriptions (
  signum,
  name, 
  name_en,
  alternative_signum,
  location,
  parish,
  municipality,
  county,
  landscape,
  country,
  coordinates,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  style_group,
  period_start,
  period_end,
  dating_text,
  historical_context,
  scholarly_notes,
  raa_number,
  current_location
) VALUES (
  'U 489',
  'Laggastenen',
  'Lagga Stone', 
  ARRAY['L 570', 'B 207'],
  'Morby, Lagga socken (ursprunglig plats)',
  'Lagga socken',
  'Knivsta',
  'Uppsala län',
  'Uppland',
  'Sverige',
  POINT(17.6315, 59.8577),
  'khulu · lit · kira · bro fr ant · kilaua · totur · sin · uk sum · ati · ulfr · ybiʀ risti',
  'Gullaug(?) let gæra bro fyr and Gillaugaʀ, dottur sinnaʀ ok sum atti Ulfʀ. Øpiʀ risti.',
  'Gullaug(?) had the bridge made for the spirit of Gillaug, her daughter, and whom Ulfr owned (i.e. was married to). Œpir carved.',
  'runsten',
  'granit',
  'Pr 4',
  725,
  1100,
  'Vikingatid (725-1100)',
  'Handlar om brobyggnad som kristen god gärning för de döda. Ristad av den berömde runmästaren Öpir. Hämtades från Mora äng, Lagga, år 1729. Visades vid världsutställningen i Paris 1867.',
  'Signerad av Öpir, en av de mest kända runmästarna. Exempel på kristen runsten där brobyggnad ses som god gärning för den avlidnas själ. Flyttad från ursprungsplatsen 1729.',
  'RAÄ 1:7',
  'Universitetsparken, Uppsala'
);