-- Lägg till Sö 106 (Kjula-stenen) - en av de mest berömda runstenarna
INSERT INTO runic_inscriptions (
  signum,
  name, 
  name_en,
  alternative_signum,
  location,
  parish,
  province,
  country,
  coordinates,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  dimensions,
  style_group,
  period_start,
  period_end,
  historical_context,
  scholarly_notes
) VALUES (
  'Sö 106',
  'Kjula-stenen',
  'Kjula Stone', 
  ARRAY['L 979', 'B 753'],
  'Kungshållet på Kjula ås, Kjula socken',
  'Kjula',
  'Södermanland', 
  'Sverige',
  POINT(16.67203, 59.38337),
  'alrikʀ ¤ raisti ¤ stain × sun × siriþaʀ × at × sin faþur × sbiut ×× saʀ × uisitaula × um × uaʀit : hafþi × burg × um brutna : i : auk × um barþa +× firþ × han × kar(s)aʀ + kuni + alaʀ ×',
  'Alrik reste stenen, Sigrids son, efter sin fader Spjut. Han västerut varit hade, borg han brutit och besegrat. ... han kände alla.',
  'Alríkr, Sigríðr''s son, raised the stone in memory of his father Spjót, who had been in the west, broken down and fought in townships. He knew all the journey''s fortresses.',
  'runestone',
  'granit',
  '3,4 m hög, 1,25 m bred, 0,4 m tjock',
  'Pr1',
  1010,
  1050,
  'Troligen ristad av samma runristare som Sigurdsristningen. Södermanlands största runsten. Står troligen på sin ursprungliga plats.',
  'En av Sveriges mest berömda runstenar. Omnämner vikingafärder västerut och strider. Innehåller både långkvistrunor och stavlösa runor. Runhöjd 10-15 cm.'
);