-- Add missing Uppsala runestones U 800-U 1181 and additional ones
INSERT INTO public.runic_inscriptions (
  signum, name, location, parish, province, country, municipality, county, landscape,
  period_start, period_end, current_location, created_at, updated_at
) VALUES
-- U 800-U 850
('U 800', 'Upplands runinskrifter 800', 'Långtora kyrka', 'Långtora', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Långtora kyrka', now(), now()),
('U 801', 'Upplands runinskrifter 801', 'Långtora prästgård', 'Långtora', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Långtora prästgård', now(), now()),
('U 802', 'Upplands runinskrifter 802', 'Långtora gärde', 'Långtora', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Långtora gärde', now(), now()),
('U 803', 'Upplands runinskrifter 803', 'Långtora by', 'Långtora', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Långtora by', now(), now()),
('U 804', 'Upplands runinskrifter 804', 'Långtora by', 'Långtora', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Långtora by', now(), now()),
('U 805', 'Upplands runinskrifter 805', 'Fröslunda kyrka', 'Fröslunda', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Fröslunda kyrka', now(), now()),
('U 807', 'Upplands runinskrifter 807', 'Eneberga', 'Fröslunda', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Fröslunda kyrka', now(), now()),
('U 808', 'Upplands runinskrifter 808', 'Eneberga, Hamra', 'Fröslunda', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Eneberga, Hamra', now(), now()),
('U 809', 'Upplands runinskrifter 809', 'Härvesta, Nopskäl', 'Fröslunda', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Härvesta, Nopskäl', now(), now()),
('U 810', 'Upplands runinskrifter 810', 'Nopskäl', 'Fröslunda', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Nopskäl', now(), now()),
('U 811', 'Upplands runinskrifter 811', 'Hjälsta kyrka', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Hjälsta kyrka', now(), now()),
('U 812', 'Upplands runinskrifter 812', 'Hjälsta kyrka', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Hjälsta kyrka', now(), now()),
('U 813', 'Upplands runinskrifter 813', 'Brunnsta', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Brunnsta', now(), now()),
('U 814', 'Upplands runinskrifter 814', 'Bälsunda', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Bälsunda', now(), now()),
('U 815', 'Upplands runinskrifter 815', 'Bälsunda', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Bälsunda', now(), now()),
('U 816', 'Upplands runinskrifter 816', 'Bälsunda', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Bälsunda', now(), now()),
('U 817', 'Upplands runinskrifter 817', 'Bälsunda', 'Hjälsta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Bälsunda', now(), now()),
('U 818', 'Upplands runinskrifter 818', 'Gryta', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Gryta', now(), now()),
('U 819', 'Upplands runinskrifter 819', 'Mysinge', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Mysinge', now(), now()),
('U 820', 'Upplands runinskrifter 820', 'Mysinge', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Mysinge', now(), now()),
('U 821', 'Upplands runinskrifter 821', 'Mysinge', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Mysinge', now(), now()),
('U 822', 'Upplands runinskrifter 822', 'Rävsta', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Rävsta', now(), now()),
('U 823', 'Upplands runinskrifter 823', 'Rävsta', 'Kulla', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Rävsta', now(), now()),
('U 824', 'Upplands runinskrifter 824', 'Holms kyrka', 'Holms', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Holms kyrka', now(), now()),
('U 825', 'Upplands runinskrifter 825', 'Gymminge', 'Holms', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Gymminge', now(), now()),
('U 826', 'Upplands runinskrifter 826', 'Mysinge', 'Holms', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Mysinge', now(), now()),
('U 827', 'Upplands runinskrifter 827', 'Valby', 'Holms', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Valby', now(), now()),
('U 828', 'Upplands runinskrifter 828', 'Bodarna', 'Fittja', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Bodarna', now(), now()),
('U 829', 'Upplands runinskrifter 829', 'Furby, Furbylund', 'Giresta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Furby, Furbylund', now(), now()),
('U 830', 'Upplands runinskrifter 830', 'Furby', 'Giresta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Furby', now(), now()),
('U 831', 'Upplands runinskrifter 831', 'Giresta by', 'Giresta', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Giresta by', now(), now()),
('U 832', 'Upplands runinskrifter 832', 'Nysätra kyrka', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Nysätra kyrka', now(), now()),
('U 833', 'Upplands runinskrifter 833', 'Nysätra kyrka', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Nysätra kyrka', now(), now()),
('U 834', 'Upplands runinskrifter 834', 'Nysätra skola', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Nysätra kyrka', now(), now()),
('U 835', 'Upplands runinskrifter 835', 'Nysätra prästgård', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Nysätra prästgård', now(), now()),
('U 836', 'Upplands runinskrifter 836', 'Alsta', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Alsta', now(), now()),
('U 837', 'Upplands runinskrifter 837', 'Alsta', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Alsta', now(), now()),
('U 838', 'Upplands runinskrifter 838', 'Ryda kungsgård', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Ryda kungsgård', now(), now()),
('U 839', 'Upplands runinskrifter 839', 'Ryda kungsgård', 'Nysätra', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Ryda kungsgård', now(), now()),
('U 840', 'Upplands runinskrifter 840', 'Dalby kyrka', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Dalby kyrka', now(), now()),
('U 841', 'Upplands runinskrifter 841', 'Dalby kyrka', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Dalby kyrka', now(), now()),
('U 842', 'Upplands runinskrifter 842', 'Hälleberga ägogräns', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Hälleberga ägogräns', now(), now()),
('U 843', 'Upplands runinskrifter 843', 'Hässle', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Hässle', now(), now()),
('U 844', 'Upplands runinskrifter 844', 'Viggeby', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Viggeby', now(), now()),
('U 845', 'Upplands runinskrifter 845', 'Viggeby', 'Dalby', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Viggeby', now(), now()),
('U 846', 'Upplands runinskrifter 846', 'Västeråkers kyrka', 'Västeråkers', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Västeråkers kyrka', now(), now()),
('U 847', 'Upplands runinskrifter 847', 'Västeråkers kyrka', 'Västeråkers', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Västeråkers kyrka', now(), now()),
('U 848', 'Upplands runinskrifter 848', 'Torresta', 'Västeråkers', 'Uppland', 'Sverige', 'Enköping', 'Uppsala', 'Uppland', 1000, 1100, 'Torresta', now(), now()),
('U 849', 'Upplands runinskrifter 849', 'Balingsta kyrka', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Balingsta kyrka', now(), now()),
('U 851', 'Upplands runinskrifter 851', 'Balingsta kyrka', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Balingsta kyrka', now(), now()),
('U 852', 'Upplands runinskrifter 852', 'Balingsta kyrka', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Balingsta kyrka', now(), now()),
('U 853', 'Upplands runinskrifter 853', 'Skolhuset', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skolhuset', now(), now()),
-- U 851-U 900  
('U 854', 'Upplands runinskrifter 854', 'Prästgården', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Prästgården', now(), now()),
('U 855', 'Bökstastenen', 'Balingsta', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Balingsta', now(), now()),
('U 856', 'Upplands runinskrifter 856', 'Frövi', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Frövi', now(), now()),
('U 857', 'Upplands runinskrifter 857', 'Frövi', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Frövi', now(), now()),
('U 858', 'Upplands runinskrifter 858', 'Kumla', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Kumla', now(), now()),
('U 859', 'Upplands runinskrifter 859', 'Måsta', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Måsta', now(), now()),
('U 860', 'Upplands runinskrifter 860', 'Måsta', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Måsta', now(), now()),
('U 861', 'Upplands runinskrifter 861', 'Norsta', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Norsta', now(), now()),
('U 862', 'Upplands runinskrifter 862', 'Säva', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Säva', now(), now()),
('U 863', 'Upplands runinskrifter 863', 'Tibble', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Tibble', now(), now()),
('U 864', 'Upplands runinskrifter 864', 'Vik', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Vik', now(), now()),
('U 865', 'Upplands runinskrifter 865', 'Vik', 'Balingsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Vik', now(), now()),
('U 866', 'Upplands runinskrifter 866', 'Björnome', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Björnome', now(), now()),
('U 867', 'Upplands runinskrifter 867', 'Gryta', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Gryta', now(), now()),
('U 868', 'Upplands runinskrifter 868', 'Ransta', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Ransta', now(), now()),
('U 869', 'Upplands runinskrifter 869', 'Salnecke, Björkendal', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Upplandsmuseet', now(), now()),
('U 870', 'Upplands runinskrifter 870', 'Säva', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Säva', now(), now()),
('U 871', 'Ölstastenen', 'Gryta', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skansen', now(), now()),
('U 872', 'Upplands runinskrifter 872', 'Ölsta', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Ölsta', now(), now()),
('U 873', 'Upplands runinskrifter 873', 'Örsunda', 'Gryta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Örsunda', now(), now()),
('U 874', 'Upplands runinskrifter 874', 'Hagby kyrka', 'Hagby', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Hagby kyrka', now(), now()),
('U 875', 'Upplands runinskrifter 875', 'Focksta', 'Hagby', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Focksta', now(), now()),
('U 876', 'Upplands runinskrifter 876', 'Focksta', 'Hagby', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Focksta', now(), now()),
('U 877', 'Möjbrostenen', 'Hagby', 'Hagby', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'SHM', now(), now()),
('U 878', 'Upplands runinskrifter 878', 'Möjbro', 'Hagby', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Möjbro', now(), now()),
('U 879', 'Upplands runinskrifter 879', 'Bragby', 'Ramsta', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Bragby', now(), now()),
('U 880', 'Upplands runinskrifter 880', 'Skogstibble kyrka', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skogstibble kyrka', now(), now()),
('U 881', 'Upplands runinskrifter 881', 'Skogstibble kyrka', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skogstibble kyrka', now(), now()),
('U 882', 'Upplands runinskrifter 882', 'Skogstibble kyrka', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skogstibble kyrka', now(), now()),
('U 883', 'Upplands runinskrifter 883', 'Prästgården', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Prästgården', now(), now()),
('U 884', 'Upplands runinskrifter 884', 'Ingla', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Ingla', now(), now()),
('U 885', 'Upplands runinskrifter 885', 'Ingla', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Ingla', now(), now()),
('U 886', 'Upplands runinskrifter 886', 'Ingla', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Uppsala', now(), now()),
('U 887', 'Upplands runinskrifter 887', 'Skillsta', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Skillsta', now(), now()),
('U 888', 'Upplands runinskrifter 888', 'Ångelsta', 'Skogs-Tibble', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Ångelsta', now(), now()),
('U 889', 'Upplands runinskrifter 889', 'Västerby', 'Ålands', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Västerby', now(), now()),
('U 890', 'Upplands runinskrifter 890', 'Österby', 'Ålands', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Österby', now(), now()),
('U 891', 'Upplands runinskrifter 891', 'Uppsala-Näs kyrka', 'Uppsala-Näs', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Uppsala-Näs kyrka', now(), now()),
('U 892', 'Upplands runinskrifter 892', 'Uppsala-Näs kyrka', 'Uppsala-Näs', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Uppsala-Näs kyrka', now(), now()),
('U 893', 'Upplands runinskrifter 893', 'Högby', 'Uppsala-Näs', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Högby', now(), now()),
('U 894', 'Upplands runinskrifter 894', 'Söderby', 'Uppsala-Näs', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Söderby', now(), now()),
('U 895', 'Upplands runinskrifter 895', 'Uppsala', 'Uppsala', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'nära Hågahögen', now(), now()),
('U 896', 'Upplands runinskrifter 896', 'Uppsala', 'Uppsala', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Universitetsparken', now(), now()),
('U 897', 'Upplands runinskrifter 897', 'Norby', 'Uppsala', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Norby', now(), now()),
('U 898', 'Upplands runinskrifter 898', 'Norby', 'Uppsala', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Norby', now(), now()),
('U 899', 'Vårdsätrastenen', 'Vårdsätra', 'Bondkyrka', 'Uppland', 'Sverige', 'Uppsala', 'Uppsala', 'Uppland', 1000, 1100, 'Vårdsätra', now(), now())

ON CONFLICT (signum) DO NOTHING;