-- Add U 360 (Gåderstastenen) with complete information
INSERT INTO runic_inscriptions (
  id,
  signum,
  name,
  name_en,
  also_known_as,
  transliteration,
  normalization,
  translation_en,
  translation_sv,
  location,
  parish,
  province,
  country,
  municipality,
  county,
  landscape,
  coordinates,
  object_type,
  material,
  current_location,
  rune_type,
  style_group,
  dating_text,
  period_start,
  period_end,
  raa_number,
  k_samsok_uri,
  historical_context,
  scholarly_notes,
  data_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'U 360',
  'Gåderstastenen',
  'Gådersta Stone',
  ARRAY['L 516', 'B 24'],
  '+ þurstain × hiak × a hili iftiʀ erinmunt × sun × sin × auk × iftiʀ kaiʀbiarn × faþur × sin',
  'Þorsteinn hjó á helli eptir Erinmund, son sinn, ok eptir Geirbjǫrn, fǫður sinn.',
  'Þorsteinn cut on the rock-slab in memory of Erinmundr, his son, and in memory of Geirbjǫrn, his father.',
  'Torsten högg på hällen efter Ärenmund sin son och efter Gerbjörn sin fader.',
  'Gådersta',
  'Skepptuna socken',
  'Uppland',
  'Sverige',
  'Sigtuna',
  'Stockholm',
  'Uppland',
  POINT(18.1167, 59.6958),
  'häll',
  'sten',
  'Ursprunglig plats (jordfast stenblock)',
  'Okänd',
  'Pr 4',
  '725–1100 (Vikingatid)',
  725,
  1100,
  '30',
  'http://kulturarvsdata.se/uu/srdb/23571ff0-d8d2-488b-aacd-0a6a581decc9',
  'Runsten U360 i Skepptuna socken (Uppland). Den s.k. Gåderstastenen är en runristning på ett jordfast stenblock från ca 1010. Verelius har i sin Scandicam Runographicam (1675) låtit avbilda stenen.',
  'Carver: Torsten (Signed). The inscription is carved on a rock-slab. FMIS-id: 10008300300001, KMR-id: ba0df5f5-566a-49aa-904f-3c917bb50b9a. Sockenkod: 0083',
  'SRDB',
  NOW(),
  NOW()
);