-- Add U 906 (lost runestone from Vänge socken) with complete information
INSERT INTO runic_inscriptions (
  id,
  signum,
  name,
  name_en,
  also_known_as,
  transliteration,
  normalization,
  translation_en,
  translation_sv,
  location,
  parish,
  province,
  country,
  municipality,
  county,
  landscape,
  coordinates,
  object_type,
  material,
  current_location,
  rune_type,
  style_group,
  dating_text,
  period_start,
  period_end,
  raa_number,
  k_samsok_uri,
  historical_context,
  scholarly_notes,
  condition_notes,
  data_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'U 906',
  'Brunna-stenen',
  'Brunna Stone',
  ARRAY['B 426', 'L 113'],
  '[tiþfr]iþ · l[it · rita · stain · iftiʀ · hulmkiʀ · s… …n · u(k)| |k-rl · uk · munkir · at · broþur · sin ·]',
  'Tíðfríðr lét rétta stein eptir Holmgeir, s[on si]nn, ok K[a]rl ok Mungerðr(?)/Mungeirr(?) at bróður sinn.',
  'Tíðfríðr had the stone erected in memory of Holmgeirr, her son; and Karl and Mungerðr(?)/Mungeirr(?) in memory of their brother.',
  'Tidfrid lät resa stenen efter Holmger sin son och Karl och Mungärd(?) efter sin broder.',
  'Brunna',
  'Vänge socken',
  'Uppland',
  'Sverige',
  'Uppsala',
  'Uppsala',
  'Uppland',
  POINT(17.4421, 59.8471),
  'runsten',
  'ljusröd granit',
  'Försvunnen - fragment dolt i marken sedan 1969',
  'Okänd',
  'Pr 5',
  '725–1100 (Vikingatid)',
  725,
  1100,
  '44',
  'http://kulturarvsdata.se/uu/srdb/d7a708d0-145c-48ca-8fea-3f846cdf3b37',
  'En numera försvunnen sten i Vänge socken i Uppland. På 1950-talet återfanns ett fragment av stenen i en stenmur men sedan 1969 är detta fragment dolt i marken. I Verelius bok Runographiam Scandicam (1675) finns stenen avbildad och merparten av ristningen är tolkad.',
  'Carver: Öpir 1 (Attributed). Ett fragment funnet 1950 i en stenmur vid mangårdsbyggnaden. FMIS-id: 10029300440001, KMR-id: 5955e567-7a2c-4d97-9fa0-d3269d9ca61e. Sockenkod: 0293',
  'Försvunnen - endast fragment kvarvarande, dolt i marken sedan 1969',
  'SRDB',
  NOW(),
  NOW()
);