-- Insert more Gotlandic runestones G 141-150
INSERT INTO runic_inscriptions (
  signum,
  location,
  parish,
  province,
  country,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  historical_context,
  scholarly_notes,
  coordinates,
  landscape
) VALUES 
(
  'G 141',
  'Halla kyrka',
  'Halla socken',
  'Gotland',
  'Sverige',
  'þoru : lit : raisa : stain : aftiR : biarn : bonta : sin : kuþ : hialbi : ant hans',
  'Tora lät resa stenen efter Björn, sin make. Gud hjälpe hans ande.',
  'Tora had the stone raised after Björn, her husband. God help his soul.',
  'runsten',
  'Kalksten',
  'Inmurad i kyrkans sydportal. En av få kvinnliga beställare på Gotland. Tora var troligen änka.',
  'Referens: s. 16, plansch 5. Halla ting.',
  POINT(18.2167, 57.4833),
  'Gotland'
),
(
  'G 142',
  'Västerhejde kyrka',
  'Västerhejde socken',
  'Gotland',
  'Sverige',
  'hrialmR : lit : raisa : stain : þina : aftiR : alrik : faþur : sin :',
  'Hjälm lät resa denna sten efter Alrik, sin fader.',
  'Hjälm had this stone raised after Alrik, his father.',
  'runsten',
  'Kalksten',
  'I långhusets västra vägg. Typiskt patriarkalisk minnessten från kristen tid.',
  'Referens: s. 17–18, plansch 6. Västerhejde ting.',
  POINT(18.3, 57.6),
  'Gotland'
),
(
  'G 143',
  'Stenkumla kyrka',
  'Stenkumla socken',
  'Gotland',
  'Sverige',
  'sila : lit : raisa : stain : þina : aftiR : auin : sun : sin',
  'Sigrid lät resa denna sten efter Övind, sin son.',
  'Sigrid had this stone raised after Övind, her son.',
  'runsten',
  'Kalksten',
  'I korets sydvägg. Kvinnonamn Sila/Sigrid. Tydlig och enkel minnesformel.',
  'Referens: s. 19, plansch 7. Stenkumla ting.',
  POINT(18.4, 57.5),
  'Gotland'
),
(
  'G 144',
  'Stenkumla kyrka',
  'Stenkumla socken',
  'Gotland',
  'Sverige',
  'stin : lit : raisa : stain : aftiR : þorkil : faþur : sin',
  'Sten lät resa stenen efter Torkel, sin fader.',
  'Sten had the stone raised after Torkel, his father.',
  'runsten',
  'Kalksten',
  'Norra långhusväggen. Ett av de vanligare runnamnen återfinns här (Torkel).',
  'Referens: s. 20, plansch 8. Stenkumla ting.',
  POINT(18.4, 57.5),
  'Gotland'
),
(
  'G 145',
  'Stenkumla kyrka',
  'Stenkumla socken',
  'Gotland',
  'Sverige',
  'kaiR : lit : raisa : stain : þina : aftiR : broþur : sin : auin',
  'Gair lät resa denna sten efter sin broder Övind.',
  'Gair had this stone raised after his brother Övind.',
  'runsten',
  'Kalksten',
  'Södra kyrkväggen. Brödraminne, typisk för vikingatidens sociala struktur.',
  'Referens: s. 21, plansch 8. Stenkumla ting.',
  POINT(18.4, 57.5),
  'Gotland'
),
(
  'G 146',
  'Stenkumla kyrka',
  'Stenkumla socken',
  'Gotland',
  'Sverige',
  'þurui : lit : raisa : stain : aftiR : biorn : sun : sin',
  'Torvi lät resa stenen efter Björn, sin son.',
  'Torvi had the stone raised after Björn, her son.',
  'runsten',
  'Kalksten',
  'Inmurad i västra långväggen. Vanligt kvinnoinitiativ. Namnet Torvi kopplas till gudanamnet Tor.',
  'Referens: s. 22, plansch 9. Stenkumla ting.',
  POINT(18.4, 57.5),
  'Gotland'
),
(
  'G 147',
  'Träkumla kyrka',
  'Träkumla socken',
  'Gotland',
  'Sverige',
  'kaiR : lit : raisa : stain : aftiR : þurbiarn : faþur : sin',
  'Gair lät resa stenen efter Torbjörn, sin fader.',
  'Gair had the stone raised after Torbjörn, his father.',
  'runsten',
  'Kalksten',
  'Östra väggen. Torbjörn är ett mycket vanligt namn i runinskrifter.',
  'Referens: s. 23, plansch 9. Träkumla ting.',
  POINT(18.5, 57.4),
  'Gotland'
),
(
  'G 148',
  'Träkumla kyrka',
  'Träkumla socken',
  'Gotland',
  'Sverige',
  'stin : lit : raisa : stain : aftiR : þialfi : broþur : sin',
  'Sten lät resa stenen efter Tjälve, sin broder.',
  'Sten had the stone raised after Tjälve, his brother.',
  'runsten',
  'Kalksten',
  'Södra väggen. Tjälve (Þjálfi) är ett namn känt från nordisk mytologi.',
  'Referens: s. 24, plansch 10. Träkumla ting.',
  POINT(18.5, 57.4),
  'Gotland'
),
(
  'G 149',
  'Träkumla kyrka',
  'Träkumla socken',
  'Gotland',
  'Sverige',
  'þurui : lit : raisa : stain : aftiR : þorkil : sun : sin',
  'Torvi lät resa stenen efter Torkel, sin son.',
  'Torvi had the stone raised after Torkel, her son.',
  'runsten',
  'Kalksten',
  'Kyrkans inre södra vägg. Liknande formulering som G 146, kvinnlig rest inskrift.',
  'Referens: s. 25, plansch 10. Träkumla ting.',
  POINT(18.5, 57.4),
  'Gotland'
),
(
  'G 150',
  'Follingbo kyrka',
  'Follingbo socken',
  'Gotland',
  'Sverige',
  'biarn : lit : raisa : stain : aftiR : þurkil : faþur : sin',
  'Björn lät resa stenen efter Torkel, sin fader.',
  'Björn had the stone raised after Torkel, his father.',
  'runsten',
  'Kalksten',
  'Inmurad i tornmuren. Fader-sonförhållande. Namnen återkommer ofta.',
  'Referens: s. 26–27, plansch 11. Follingbo ting.',
  POINT(18.3, 57.5),
  'Gotland'
)
ON CONFLICT (signum) DO UPDATE SET
  location = EXCLUDED.location,
  parish = EXCLUDED.parish,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  transliteration = EXCLUDED.transliteration,
  translation_sv = EXCLUDED.translation_sv,
  translation_en = EXCLUDED.translation_en,
  object_type = EXCLUDED.object_type,
  material = EXCLUDED.material,
  historical_context = EXCLUDED.historical_context,
  scholarly_notes = EXCLUDED.scholarly_notes,
  coordinates = EXCLUDED.coordinates,
  landscape = EXCLUDED.landscape,
  updated_at = now();