-- Lägg till Nolbystenen/Burestenen M 1 med all information
INSERT INTO runic_inscriptions (
  signum, 
  name, 
  name_en, 
  also_known_as,
  transliteration,
  translation_sv,
  translation_en,
  location,
  parish,
  municipality,
  county,
  landscape,
  country,
  period_start,
  period_end,
  dating_text,
  coordinates,
  object_type,
  material,
  current_location,
  raa_number,
  scholarly_notes,
  historical_context
) VALUES (
  'M 1',
  'Nolbystenen',
  'Nolby Stone',
  ARRAY['Burestenen', 'Bure Stone'],
  '× barksuain uk sihuastr uk friþi raistu stain ¶ þinsa '' aftiR buri faþur isin '' in farþaihn markaþi',
  'Barksven och Sigfast och Fride reste denna sten efter Bure, sin fader. Men Fartegn märkte.',
  'Barksven and Sigfast and Fride raised this stone after Bure, their father. And Fartegn carved.',
  'Nolby, 10 km söder om Sundsvall',
  'Njurunda socken',
  'Sundsvall',
  'Västernorrlands län',
  'Medelpad',
  'Sverige',
  1000,
  1099,
  '1000-talet e.Kr.',
  point(17.36094, 62.29194),
  'Runsten',
  'Sten',
  'Tunavägen/Gamla kustlandsvägen, Nolby, Njurunda socken',
  'Njurunda 116:1',
  'Ca. 160 cm hög runsten vid Nolby. Står i det reservatslika och unika fornlämningsområdet Kvissle-Nolby-Prästbolet vid Ljungans utlopp i Bottenhavet. Strax bredvid finns ruinen av ett tidigmedeltida gårdskapell, flera vikingatida gravfält och tolv storhögar från folkvandringstiden.',
  'Nolbystenens text användes som källa av Johan Bure när han gjorde sin släktbok över Bureätten. Ristad av Fartegn. Bär runor och kors från tiden vid kristendomens införande.'
);