-- Lägg till alla runstenar från Sollentuna
INSERT INTO runic_inscriptions (
  signum,
  name, 
  name_en,
  also_known_as,
  location,
  parish,
  municipality,
  county,
  landscape,
  country,
  coordinates,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  dimensions,
  style_group,
  period_start,
  period_end,
  dating_text,
  historical_context,
  scholarly_notes,
  raa_number,
  current_location
) VALUES 
-- Kummelbystenen
(
  'U Fv1953;263',
  'Kummelbystenen',
  'Kummelby Stone', 
  ARRAY['Kummelby runsten'],
  'Helenelund, Sollentuna socken',
  'Sollentuna socken',
  'Sollentuna',
  'Stockholm län',
  'Uppland',
  'Sverige',
  POINT(17.96149, 59.41578),
  'elka · lit raisa stain · eftiʀ · sua͡rtik · b... ... ... -t · eystain · uk · at · emink · suni ÷ sina · in · ikulfastr',
  'Helga lät resa stenen efter Svärting, sin man, och efter Östen och efter Häming, sina söner. Och Igulfast (ristade).',
  'Helga had the stone raised in memory of Sverting, her husband, and in memory of Östen and in memory of Häming, her sons. And Igulfast (carved).',
  'runsten',
  'grå granit med inslag av kvarts',
  '200 cm hög, 140 cm bred, 27 cm tjock',
  'Pr5 (Urnesstil)',
  950,
  1100,
  'Sent 1000-tal (vikingatid)',
  'Hittad 1953 vid byggnation. Låg på den plats som varit gårdsplan i gamla Kummelby. Ristad av Igulfast.',
  'Grävdes fram 20 oktober 1953 vid Nyodlingsvägen 4. Toppen delvis skadad med cirka 10 förlorade runor. Står nu vid Kummelby kyrka.',
  'FMIS 184:1',
  'Kummelby kyrka'
),
-- U 94 Sollentuna kyrka
(
  'U 94',
  'Sollentuna kyrksten 1',
  'Sollentuna Church Stone 1', 
  ARRAY['Sollentuna runsten 1'],
  'Sollentuna kyrka, Sollentuna socken',
  'Sollentuna socken',
  'Sollentuna',
  'Stockholm län',
  'Uppland',
  'Sverige',
  POINT(17.95000, 59.42000),
  '(l)ugi + ok kunar + litu + risa : stin + þina + iftiʀ + kiru + faþur … … halbi : hans ant',
  '[Fu]llugi(?) ok Gunnarr letu ræisa stæin þenna æftiʀ Gæiʀrøð(?), faður … [Guð] hialpi hans and.',
  'Fullugi(?) and Gunnarr had this stone raised in memory of Geirrøðr(?), (their) father. … May God help his spirit.',
  'runsten',
  'sten',
  '',
  '',
  800,
  1100,
  'Vikingatid',
  'Runsten vid Sollentuna kyrka med kristen avslutning.',
  'En av flera runstenar vid Sollentuna kyrka. Innehåller bön om Guds hjälp för den dödes själ.',
  '',
  'Sollentuna kyrka'
),
-- U 95 Sollentuna kyrka
(
  'U 95',
  'Sollentuna kyrksten 2',
  'Sollentuna Church Stone 2', 
  ARRAY['Sollentuna runsten 2'],
  'Sollentuna kyrka, Sollentuna socken',
  'Sollentuna socken',
  'Sollentuna',
  'Stockholm län',
  'Uppland',
  'Sverige',
  POINT(17.95000, 59.42000),
  '… …in + þinsa + ifti(ʀ) … ant hans þartunki',
  '… [stæ]in þennsa æftiʀ … and hans',
  '… this stone in memory of … his spirit',
  'runsten',
  'sten',
  '',
  '',
  800,
  1100,
  'Vikingatid',
  'Fragmentarisk runsten vid Sollentuna kyrka.',
  'En av flera runstenar vid Sollentuna kyrka. Delvis bevarad inskrift.',
  '',
  'Sollentuna kyrka'
),
-- U Fv1959;250 Sollentuna kyrka
(
  'U Fv1959;250',
  'Sollentuna kyrksten 3',
  'Sollentuna Church Stone 3', 
  ARRAY['Sollentuna runsten 3'],
  'Sollentuna kyrka, Sollentuna socken',
  'Sollentuna socken',
  'Sollentuna',
  'Stockholm län',
  'Uppland',
  'Sverige',
  POINT(17.95000, 59.42000),
  '… stai- …- · ebt… … (a)nt … …u…',
  '… stæi[n] … æft[iʀ] … and … …',
  '… stone … in memory of … spirit …',
  'runsten',
  'sten',
  '',
  '',
  800,
  1100,
  'Vikingatid',
  'Fragmentarisk runsten vid Sollentuna kyrka, funnen 1959.',
  'En av flera runstenar vid Sollentuna kyrka. Mycket fragmentarisk bevarad inskrift.',
  '',
  'Sollentuna kyrka'
),
-- U Fv1968;279B Sollentuna kyrka
(
  'U Fv1968;279B',
  'Sollentuna kyrksten 4',
  'Sollentuna Church Stone 4', 
  ARRAY['Sollentuna runsten 4'],
  'Sollentuna kyrka, Sollentuna socken',
  'Sollentuna socken',
  'Sollentuna',
  'Stockholm län',
  'Uppland',
  'Sverige',
  POINT(17.95000, 59.42000),
  '-ikfastr : ak × une… … …a × eftiʀ × iluka × fþu… …',
  '[S]igfastr ok Onæ[mʀ] … … æftiʀ Illuga, faðu[r] …',
  'Sigfastr and Ónæmr … in memory of Illugi, (their) father …',
  'runsten',
  'sten',
  '',
  '',
  800,
  1100,
  'Vikingatid',
  'Fragmentarisk runsten vid Sollentuna kyrka, funnen 1968.',
  'En av flera runstenar vid Sollentuna kyrka. Nämner Sigfastr och Ónæmr som resare av stenen.',
  '',
  'Sollentuna kyrka'
);