-- Add Gotlandic runic inscriptions from Öja, Fide, Näs, and Grötlingbo churches

INSERT INTO public.runic_inscriptions (
  signum, 
  name, 
  name_en,
  transliteration,
  translation_en,
  translation_sv,
  location,
  parish,
  municipality,
  county,
  landscape,
  country,
  coordinates,
  object_type,
  material,
  dating_text,
  period_start,
  period_end,
  cultural_classification,
  data_source
) VALUES 

-- G 21 - Öja kyrka
(
  'G 21',
  'Öja kyrka',
  'Öja Church',
  '⁓ iakaubs : synir : a burh : litu : g(i)(a)(r)a : stain : yvir : faþur : sen : ok : [b]roþur : sen : hera : [ni]kulas : sum : (o)ra : (k)irkiu : ati : men : guþ : uildi : biþ[i]n : fyri : þ(a)ira : sialum : ok : hehualdi : … : syni : þair : huilas : hier : undir · o^le : (l)uþa^r : gia^rþi : mik',
  'Jakobr of Burg/Burge''s sons had the stone made over their father and their brother, Sire Nikulás, who owned our church (= was its paster) while God willed it. Pray for their souls and for Hegvaldr … son. They are resting hereunder. Óli/Olli <luþar> made me.',
  'Jakobs söner på Burg lät göra stenen över sin fader och sin broder, herr Nikulas, som ägde vår kyrka (dvs. var kyrkoherde vid vår kyrka), så länge Gud ville. Bedjen för deras själar och för Hägvald, … son. De vilar här under. Ole <luþar> gjorde mig.',
  'Öja kyrka, Öja socken',
  'Öja',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3002, 57.0351), 4326),
  'gravhäll',
  'gråvit kalksten',
  '1266–1333, slutet av 1200-talet – början av 1300-talet',
  1266,
  1333,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 24 - Öja kyrka (fragment)
(
  'G 24',
  'Öja kyrka',
  'Öja Church',
  '… sta-- y---r sen : s…',
  '… the stone over his/her son.',
  '… stenen över sin son …',
  'Öja kyrka, Öja socken',
  'Öja',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3, 57.0355), 4326),
  'fragment av gravhäll',
  'kalksten',
  '1100–1500, medeltid',
  1100,
  1500,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 25/G 22 - Öja kyrka
(
  'G 25',
  'Öja kyrka',
  'Öja Church',
  '[+ hiar : huilis : untir : rinm:untr :] i [o]yu : biþin [: aler : furir … herra : naþ : hab… sial … kiara : beta(r) : hinsarfa :] … ok : …h : am[e(n)]',
  'Hereunder rests …-mundr in Eyjr/Öja. All pray for … Lord''s grace … soul … Pétar (of) Hinsarfr/Hinsarfi made. … and … amen.',
  'Här under vilar …-mund i Öja. Bedjen alla för … Herres nåd … själ … göra Peter Hinsarve.',
  'Öja kyrka, Öja socken',
  'Öja',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3, 57.0355), 4326),
  'gravhäll',
  'röd kalksten',
  '1350–1400, andra hälften av 1300-talet – omkring 1400',
  1350,
  1400,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 26 - Öja kyrka
(
  'G 26',
  'Öja kyrka',
  'Öja Church',
  '⁓ …kl : ai--era-…tae… : …k--…',
  '…',
  '…',
  'Öja kyrka, Öja socken',
  'Öja',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3007, 57.0357), 4326),
  'gravhäll',
  'kalksten',
  '1100–1500, medeltid',
  1100,
  1500,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 27 - Öja kyrka
(
  'G 27',
  'Öja kyrka',
  'Öja Church',
  '…al--…ri… ok b--a^r kiarþu mik',
  '… and Pétar(?) made me.',
  '… och … gjorde mig.',
  'Öja kyrka, Öja socken',
  'Öja',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3005, 57.0351), 4326),
  'gravhäll',
  'kalksten',
  '1266–1333, slutet av 1200-talet – början av 1300-talet',
  1266,
  1333,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 28 - Fide kyrka
(
  'G 28',
  'Fide kyrka',
  'Fide Church',
  '(h)(e)(h)laikr : kiarþ:i stan (þ)ani [: …(r)(i)(n) :] ok : auþulfr :: þaiʀ litu : g[i(a)^(r)… …]',
  'Hegleikr made this stone. Katrín(?) and Auðulfr, they had (it) made …',
  'Häglaik gjorde denna sten … Katrin(?) och Audulv de lät göra …',
  'Fide kyrka, Fide socken',
  'Fide',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3164, 57.0737), 4326),
  'gravhäll',
  'rödgrå kalksten',
  '1100–1366, senast mitten av 1300-talet',
  1100,
  1366,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 31 - Fide kyrka (putsinskrift)
(
  'G 31',
  'Fide kyrka',
  'Fide Church',
  '§A ihesus : na(s)arenus ¶ iacobus ¶ lu (l)aurencius ¶ m(u)ttonmu- §B olauir §C þauþi : i braiþu^ki(u)(m)',
  'Jesus of Nazareth, Jacob … Laurentius … Ólafr Þjóði in Breíðukvíum/Bredkvie.',
  'Jesus nasarenus. Jacobus. … Laurentius … Olav. Tjaude i Bredkvide.',
  'Fide kyrka, Fide socken',
  'Fide',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3164, 57.0737), 4326),
  'putsinskrift',
  'kalkputs',
  '1400–1499, 1400-talet',
  1400,
  1499,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 32 - Anderse/Öja kyrka (fragment)
(
  'G 32',
  'Anderse (nu Öja kyrka)',
  'Anderse (now Öja Church)',
  '…o : sunutahr … …--…',
  '… Sunday …',
  '… <o> söndag (dvs. söndagsbokstav för året) …',
  'Anderse, Fide socken (nu under tak utanför Öjas kyrkogårdsmur)',
  'Fide',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3, 57.0355), 4326),
  'fragment av gravhäll',
  'grå kalksten',
  '1300–1499, 1300-talet – 1400-talet',
  1300,
  1499,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 33 - Näs kyrka
(
  'G 33',
  'Näs kyrka',
  'Näs Church',
  '+ ruþui : af ronum : hehuiþa burna : i hangnasteþu- : (h)(a)(n) lit gera stain : yuir sen : husbonda botulf (o)k o^laf sen su^n biþin firi þaira sialum',
  'Hróðvé of Ronir/Rone, child of Hegviðr in Hagnastaðir/Hagnestäde, she had the stone made over her husband Bótulfr and Ólafr, her son. Pray for their souls.',
  'Rudvi från Rone, dotter till Hägvid i Hagnestäde, hon lät göra stenen över sin man Botulv och sin son Olav. Bedjen för deras själar.',
  'Näs kyrka, Näs socken',
  'Näs',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.2625, 57.1102), 4326),
  'gravhäll',
  'ljusgrå kalksten',
  '1300–1399, 1300-talet',
  1300,
  1399,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 34 - Näs kyrka (fragment)
(
  'G 34',
  'Näs kyrka',
  'Näs Church',
  '+ -ik-(i)(þ)(r) : kr-k(u)-(r)fi h-- lit gera hua-… …þiauþu : sina : husfruy… … synir : … : (k)---uiþi… +',
  'Líknviðr(?) Krákuarfi(?)/Kråkarve(?), he had the vault made … …-þjóð, his wife … sons …',
  '… Han lät göra gravvalv … -djaud , sin hustru … söner …',
  'Näs kyrka, Näs socken',
  'Näs',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.2625, 57.1102), 4326),
  'fragment av gravhäll',
  'rödaktig kalksten',
  '1300–1399, 1300-talet',
  1300,
  1399,
  'medieval',
  'Samnordisk runtextdatabas'
),

-- G 35 - Grötlingbo kyrka
(
  'G 35',
  'Grötlingbo kyrka',
  'Grötlingbo Church',
  '[+ b(o)tair mais(t)eri : kiarþi : stain : epter : bo]taaþi : ho^usfreu sina : iakus : burnu l : uetabrhum : uar hera : naþi : þaira sial : (a)ltra : [me(n)is--air(a)] oli : hiak r:unir þisar : þesun : buais',
  'Master Bótgeirr made the stone in memory of Bótheiðr, his housewife, child of Jakobr in Vetaborg/Vätaburg. May Our Lord be gracious to all of their souls, all persons''(?). Óli/Olli cut these runes, the slave''s son of Bótgeirr(?).',
  'Botair mästare gjorde stenen efter Botaid, sin hustru, dotter till Jakob i Vetaborg. Vår Herre vare nådig alla deras själar … Ole högg dessa runor …',
  'Grötlingbo kyrka, Grötlingbo socken',
  'Grötlingbo',
  'Gotland',
  'Gotland',
  'Gotland',
  'Sweden',
  ST_SetSRID(ST_MakePoint(18.3467, 57.1335), 4326),
  'gravhäll',
  'röd kalksten',
  '1350–1400, ca. 1350–1400',
  1350,
  1400,
  'medieval',
  'Samnordisk runtextdatabas'
);