-- Add detailed Bohuslän runestones
INSERT INTO runic_inscriptions (
  signum, name, name_en, transliteration, normalization, 
  translation_sv, translation_en, location, parish, municipality, county, province, country,
  coordinates, period_start, period_end, dating_text, 
  object_type, material, current_location, 
  rune_type, historical_context, scholarly_notes,
  data_source, created_at, updated_at
) VALUES 
-- Bo Hoga
('Bo Hoga', 'Hoga-stenen', 'Hoga Stone', 
 'HauR/iauR i * am * tain won/þon iar o mul=a *', 
 'Hor/Jor i år gjorde sten vån/vån här å mulen',
 'Hor / Jor i år gjorde stenen här på mulen', 
 'Hor / Jor in the year made the stone here on the mound',
 'Hoga', 'Hoga', 'Orust', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.69902, 58.159175), 
 700, 900, '800-talet',
 'runsten', 'sten', 'Beteshage vid Hoga',
 'yngre_runor', 
 'Den enda kända runstenen på Orust, känd sedan 1643. Står i en beteshage och är lätt att nå från parkering för besökande till fornminnesområdet med domarringar och järnåldersgravar.',
 'Runstenen från 800-talet, del av större fornminnesområde',
 'NIYR', now(), now()),

-- Bo Kalleby  
('Bo Kalleby', 'Kalleby-stenen', 'Kalleby Stone',
 'þrawijan * haitinaz was', 
 'þrawijan haitinaz was',
 '-', 
 '-',
 'Kalleby, Tanums socken', 'Tanum', 'Tanum', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.332824, 58.716508),
 160, 400, '160-400 e.Kr.',
 'runsten', 'sten', 'Vid vägkanten mitt emot Tanums kyrka',
 'urnordiska_runor',
 'Runsten från perioden 160-400 ristad med urnordiska runor. Står sedan 1886 vid vägkanten mitt emot Tanums kyrka. Tidigare låg den som spång över en bäck vid Kalleby.',
 'Tolkningen av texten är mycket osäker. Urnordisk period.',
 'NIYR', now(), now()),

-- Bo NIYR 1
('Bo NIYR 1', 'Brastads kyrka', 'Brastad Church',
 'ma=ria mær h...e þæim er þena stæin kerþe',
 'Maria mær hjalpe þeim er þenna stein gerði',
 'Jungfru Maria hjälpe honom som gjorde denna sten',
 'Virgin Mary help him who made this stone',
 'Brastads kyrka', 'Brastad', 'Lysekil', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.50039, 58.395438),
 1050, 1200, 'medeltid',
 'gravhäll', 'sten', 'Inmurad i södra sidan av tornets yttersida',
 'medeltida_runor',
 'Gravhäll av eskilstunakista, inmurad i södra sidan av tornets yttersida, närmast ovanför grunden.',
 'Del av eskilstunakista, kristet motiv med bön till Jungfru Maria',
 'NIYR', now(), now()),

-- Bo NIYR 2
('Bo NIYR 2', 'Kareby kyrka', 'Kareby Church', 
 'raþe sa er kan namn orklaski k=r=a=k',
 'ræði sá er kann nafn Þorbjörn Krakr',
 'Läs den som kan namnet Torbjörn Krak',
 'Read [this] who can [read] the name Torbjörn Krak',
 'Kareby kyrka', 'Kareby', 'Uddevalla', 'Västra Götalands län', 'Bohuslän', 'Sverige', 
 point(11.912126, 57.910345),
 1100, 1200, '1100-talet',
 'dopfunt', 'sten', 'Kareby kyrka',
 'medeltida_runor',
 'Dopfunten står i Kareby kyrka. Namnet Torbjörn är skrivet med förskjutningsschiffer, Krak med en komplicerad bindruna.',
 'Intressant exempel på lönnrunor och avancerade bindrunor från medeltiden',
 'NIYR', now(), now()),

-- Bo NIYR 3
('Bo NIYR 3', 'Norums kyrka', 'Norum Church',
 'svæn : kærðe (m)',
 'Sveinn gerði [mik]', 
 'Sven gjorde m[ig]',
 'Sven made m[e]',
 'Norums kyrka', 'Norum', 'Uddevalla', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.0, 58.0),
 1050, 1150, '1100-talet',
 'dopfunt', 'sten', 'Historiska museet i Stockholm',
 'medeltida_runor',
 'Den fyrkantiga dopfunten återfanns sönderslagen på kyrkogården vid renovering 1847. Under runinskriften syns framställning av Gunnar i ormgropen från Völsungasagan.',
 'Ristare: Sven. Kombinerar runor med mytologisk bildframställning från Völsungasagan. Samma typ av lönnrunor som på Grönlandsstenen.',
 'NIYR', now(), now()),

-- Bo NIYR 4  
('Bo NIYR 4', 'Utby', 'Utby',
 'asa fu(þ)or / fu(u)or',
 'Ása/æsir fuþor',
 'Åsa / gudarna ...',
 'Åsa / the gods ...',
 'Utby, Herrestads socken', 'Herrestad', 'Uddevalla', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.766894, 58.338720),
 800, 1100, 'vikingatid-tidig medeltid',
 'hällristning', 'berg', 'Berghäll vid Utby gård',
 'runor',
 'Ristning på berghäll, någon decimeter under en hällristning 250 m söder om Utby gård i beteshage.',
 'Kort inskrift med personnamn eller gudareferens, kombination med äldre hällristningar',
 'NIYR', now(), now()),

-- Bo NIYR 7
('Bo NIYR 7', 'Kleva', 'Kleva',
 'fuþor{K}hniastbmlyøkhp : ion : a mik',
 'fuþork... Jón á mik', 
 'Jon äger mig',
 'Jon owns me',
 'Kleva, Båtslycke, Spekeröds socken', 'Spekeröd', 'Uddevalla', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.0, 58.0),
 1000, 1200, '1000-1200',
 'trissa', 'täljsten', 'Götborgs stadsmuseum',
 'runor',
 'Trissa av täljsten med ägarnamn och runrad.',
 'Praktiskt föremål med ägarnamn, visar användning av runor i vardagssammanhang',
 'NIYR', now(), now()),

-- Bo Rävsal
('Bo Rävsal', 'Rävsal-stenen', 'Rävsal Stone',
 'Hariwulfs/Hariþulfs * staina-',
 'Hariwulfs/Hariþulfs steinar',
 'Hreidulfs / Herjulfs stenar', 
 'Hreidulf''s / Herjulf''s stones',
 'Rävsal, Valla socken', 'Valla', 'Tjörn', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.734453, 58.066200),
 800, 1050, 'vikingatid',
 'runsten', 'sten', 'Vid gården Rävsal på Tjörns norra del',
 'yngre_runor',
 'Runstenen står vid gården Rävsal på Tjörns norra del ca 3 km NNO om Valla kyrka, 200 m N om väg 160. Stod ursprungligen troligen närmare vattnet.',
 'Pluralform "stenar" kan tyda på att det funnits flera stenar på platsen',
 'NIYR', now(), now()),

-- Bo Tossene
('Bo Tossene', 'Tossene-fragmentet', 'Tossene Fragment',
 '-',
 '-',
 '-',
 '-', 
 'Tossene', 'Tossene', 'Sotenäs', 'Västra Götalands län', 'Bohuslän', 'Sverige',
 point(11.0, 58.0),
 800, 1200, 'vikingatid-medeltid',
 'stenfragment', 'sten', 'Tossene kyrkas vapenhus',
 'runor',
 'Stenfragment med runor och andra tecken. Påträffades vid torpet Mulekärr och ska komma från en hög på Valla hed söder om Överby prästgård.',
 'Otolkat fragment, okänd inskrift. Klammad till södra väggen i kyrkans vapenhus',
 'NIYR', now(), now())

ON CONFLICT (signum) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  transliteration = EXCLUDED.transliteration,
  normalization = EXCLUDED.normalization,
  translation_sv = EXCLUDED.translation_sv,
  translation_en = EXCLUDED.translation_en,
  location = EXCLUDED.location,
  parish = EXCLUDED.parish,
  municipality = EXCLUDED.municipality,
  county = EXCLUDED.county,
  province = EXCLUDED.province,
  coordinates = EXCLUDED.coordinates,
  period_start = EXCLUDED.period_start,
  period_end = EXCLUDED.period_end,
  dating_text = EXCLUDED.dating_text,
  object_type = EXCLUDED.object_type,
  material = EXCLUDED.material,
  current_location = EXCLUDED.current_location,
  rune_type = EXCLUDED.rune_type,
  historical_context = EXCLUDED.historical_context,
  scholarly_notes = EXCLUDED.scholarly_notes,
  data_source = EXCLUDED.data_source,
  updated_at = now();