-- Insert Gotlandic runestones from Halla kyrka
INSERT INTO runic_inscriptions (
  signum,
  location,
  parish,
  province,
  country,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  historical_context,
  scholarly_notes,
  coordinates,
  landscape
) VALUES 
(
  'G 138',
  'Halla kyrka',
  'Halla socken',
  'Gotland',
  'Sverige',
  '... rti : legiR : koþr n a :has : lit : rist :kuml : a - : kaiRielmR :... : ainika :sun : ... trabu : leybika - :... naR : a t : feþrka : baþa : kuþ : - e ...',
  '... god läkare(?)... hans hustru lät rista (el. resa) minnesmärket efter Gairhjälm... deras ende son dräpte lybeckare. ... stenar(?) efter far och son, de båda. Gud hjälpe ...',
  '... good physician(?)... his wife had the memorial carved (or raised) after Gairhjälm... their only son killed Lübeckers. ... stones(?) after father and son, both of them. God help ...',
  'runsten',
  'Kalksten',
  'Två fragment inmurade i korets sydöstra hörnkedja, ca 3 m över markytan. Avvikande stil. Nämner lybska handelsmän, personnamn Gairhjälm. Troligen från ca 1100.',
  'Referens: s. 5–9, plansch 1–2. Halla ting.',
  POINT(18.2167, 57.4833),
  'Gotland'
),
(
  'G 139a',
  'Halla kyrka',
  'Halla socken',
  'Gotland',
  'Sverige',
  ': isifR : lit : raisa : stain : þina : aftiR : kaiRilf : sun : sin : kuþ : help : ant hans :',
  'Isäfr lät resa denna sten efter Gairälv, sin son. Gud hjälpe hans ande.',
  'Isäfr had this stone raised after Gairälv, his son. God help his soul.',
  'runsten',
  'Kalksten',
  'Inmurad i korets sydvästra hörnkedja, ca 3 m över markytan. Typisk kristen inskrift med vädjan till Gud. Isäfr är ett ovanligt namn.',
  'Referens: s. 10–12, plansch 3. Halla ting.',
  POINT(18.2167, 57.4833),
  'Gotland'
),
(
  'G 139b',
  'Halla kyrka',
  'Halla socken',
  'Gotland',
  'Sverige',
  ': tuki : lit : raisa : stain : þina : aftiR : þair : kaiRilf : sun : sin :',
  'Toke lät resa denna sten efter den där Gairälv, sin son.',
  'Toke had this stone raised after that Gairälv, his son.',
  'runsten',
  'Kalksten',
  'Inmurad i långhusets norra vägg. Fortsättning eller parallellinskrift till G 139a. Liknande namn och språk.',
  'Referens: s. 13, plansch 3. Halla ting.',
  POINT(18.2167, 57.4833),
  'Gotland'
),
(
  'G 140',
  'Halla kyrka',
  'Halla socken',
  'Gotland',
  'Sverige',
  ': kubl : þisa : raistr : aftiR : auþbiorg : sun : sin :',
  'Detta minnesmärke är rest efter Ödbjörn, sin son.',
  'This memorial is raised after Ödbjörn, his son.',
  'runsten',
  'Kalksten',
  'Inmurad i långhusets sydvägg. Vanlig minnesformel, manlig individ nämns. Enkel men tydlig.',
  'Referens: s. 14–15, plansch 4. Halla ting.',
  POINT(18.2167, 57.4833),
  'Gotland'
)
ON CONFLICT (signum) DO UPDATE SET
  location = EXCLUDED.location,
  parish = EXCLUDED.parish,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  transliteration = EXCLUDED.transliteration,
  translation_sv = EXCLUDED.translation_sv,
  translation_en = EXCLUDED.translation_en,
  object_type = EXCLUDED.object_type,
  material = EXCLUDED.material,
  historical_context = EXCLUDED.historical_context,
  scholarly_notes = EXCLUDED.scholarly_notes,
  coordinates = EXCLUDED.coordinates,
  landscape = EXCLUDED.landscape,
  updated_at = now();