-- Add U 614 (Torsätrastenen) with complete information
INSERT INTO runic_inscriptions (
  id,
  signum,
  name,
  name_en,
  also_known_as,
  transliteration,
  normalization,
  translation_en,
  translation_sv,
  location,
  parish,
  province,
  country,
  municipality,
  county,
  landscape,
  coordinates,
  object_type,
  material,
  current_location,
  rune_type,
  style_group,
  dating_text,
  period_start,
  period_end,
  raa_number,
  k_samsok_uri,
  historical_context,
  scholarly_notes,
  data_source,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'U 614',
  'Torsätrastenen',
  'Torsätra Stone',
  ARRAY['L 325', 'B 271'],
  '· skuli · auk · folki · lata · reisa · þinsa · stein · iftʀ · broþur · sin · husbiorn · hn us| |siok · uti · þa þiʀ · kialt · toku · a kutlanti ·',
  'Skúli ok Folki láta reisa þenna stein eptir bróður sinn Húsbjǫrn/Ásbjǫrn. Hann var sjúkr úti, þá þeir gjald tóku á Gotlandi.',
  'Skúli and Folki have raised this stone in memory of their brother Húsbjǫrn/Ásbjǫrn. He was sick abroad when they took payment on Gotland.',
  'Skule och Folke lät resa denna sten efter sin broder Husbjörn/Asbjörn. Han var sjuk ute när de tog skatt på Gotland.',
  'Torsätra',
  'Västra Ryds socken',
  'Uppland',
  'Sverige',
  'Upplands-Bro',
  'Stockholm',
  'Uppland',
  ST_GeomFromText('POINT(17.7668 59.5744)', 4326),
  'runsten',
  'granit',
  'SHM (Statens historiska museum)',
  'Okänd',
  'Pr 3',
  '725–1100 (Vikingatid)',
  725,
  1100,
  '65',
  'http://kulturarvsdata.se/uu/srdb/7584fb41-3944-4f94-bf6a-46a6d420ccfe',
  'One of two runestones that originally stood at the border of what later became known as Torsätra Manor, but which during the Viking Age may have been called Husa. Both stones were moved to the Swedish History Museum in 1967. The inscription tells us that Husbjörn took part in an expedition from the mainland to the island to collect tribute. The event aligns with a passage in the medieval Gutasaga, which recounts an old agreement between the Gotlanders and the Svear (Swedes).',
  'The ornamentation, the shape of the runes, and the inscription reveal that the stone was carved by Visäte sometime in the final decades of the 11th century. Carver: Visäte (Attributed). FMIS-id: 10011600650001, KMR-id: de7e17af-8e72-4367-8399-c8e24ad7670d',
  'SRDB',
  NOW(),
  NOW()
);