-- Insert Norwegian runic inscriptions that are missing from the database

-- Insert Norwegian runic inscriptions from the official list
INSERT INTO runic_inscriptions (
  signum, country, location, parish, province, period_start, period_end, 
  object_type, material, status, data_source, created_at, updated_at
) VALUES
-- Main N series
('N 1', 'Norway', 'Askim kirke', 'Askim', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 7', 'Norway', 'Skjeberg kirke', 'Skjeberg', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 8', 'Norway', 'Skjeberg kirke', 'Skjeberg', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 13', 'Norway', 'Tose, Torsnes', 'Torsnes', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 14', 'Norway', 'Tose, Torsnes', 'Torsnes', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 28', 'Norway', 'Korsøygarden, Tangen', 'Tangen', 'Vestfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 29', 'Norway', 'Nørstebø, Lesja', 'Lesja', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 61', 'Norway', 'Alstad, Hof', 'Hof', 'Vestfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 62', 'Norway', 'Alstad, Hof', 'Hof', 'Vestfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 68', 'Norway', 'Dynna, Gran', 'Gran', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 108', 'Norway', 'Lunder kirke', 'Lunder', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 130', 'Norway', 'Rauland, Uvdal', 'Uvdal', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 137', 'Norway', 'Oseberg, Slagen', 'Slagen', 'Vestfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 157', 'Norway', 'Flatdal kyrka', 'Flatdal', 'Telemark', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 172', 'Norway', 'Nesland kyrka', 'Nesland', 'Telemark', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 184', 'Norway', 'Galteland, Evje', 'Evje', 'Aust-Agder', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 188', 'Norway', 'Hoftuft, Valle', 'Valle', 'Aust-Agder', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 189', 'Norway', 'Rike, Valle', 'Valle', 'Aust-Agder', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 228', 'Norway', 'Tu, Klepp', 'Klepp', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 230', 'Norway', 'Reve, Bore', 'Bore', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 236', 'Norway', 'Sele, Bore', 'Bore', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 239', 'Norway', 'Stangeland, Høiland', 'Høiland', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 244', 'Norway', 'Helland, Sola', 'Sola', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 245', 'Norway', 'Helland 3, Sola', 'Sola', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 249', 'Norway', 'Bø, Randaberg', 'Randaberg', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 251', 'Norway', 'Mariakirken, Stavanger', 'Stavanger', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 252', 'Norway', 'Stavanger', 'Stavanger', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 257', 'Norway', 'Talgje kyrka', 'Talgje', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 258', 'Norway', 'Talgje kyrka', 'Talgje', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 259', 'Norway', 'Sørbø, Rennesøy', 'Rennesøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 262', 'Norway', 'Bru, Mosterøy', 'Mosterøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 263', 'Norway', 'Bru, Mosterøy', 'Mosterøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 264', 'Norway', 'Utstein kloster, Mosterøy', 'Mosterøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 265', 'Norway', 'Utstein kloster, Mosterøy', 'Mosterøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 268', 'Norway', 'Sandeid kyrka', 'Sandeid', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 348', 'Norway', 'Borgund kyrka I', 'Borgund', 'Sogn og Fjordane', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 384', 'Norway', 'Stedje kyrka', 'Stedje', 'Sogn og Fjordane', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 541', 'Norway', 'Norge', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 548', 'Norway', 'Alshus, Kråkerøy', 'Kråkerøy', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 549', 'Norway', 'Hallvardskirken, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),

-- Gol Kyrka series
('N 568', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 569', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 570', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 571', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 572', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 573', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 574', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 575', 'Norway', 'Gol Kyrka', 'Gol', 'Buskerud', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),

('N 582', 'Norway', 'Uppstad, Hylestad', 'Hylestad', 'Aust-Agder', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 583', 'Norway', 'Hesby kyrka', 'Hesby', 'Sogn og Fjordane', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N 584', 'Norway', 'Hesby kyrka', 'Hesby', 'Sogn og Fjordane', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),

-- Bryggen Bergen series
('N 603', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 605', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 610', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 617', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 622', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 628', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 631', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 633', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 637', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 640', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 649', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 650', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 651', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 652', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 653', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 654', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 657', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 660', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 661', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 662', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 665', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 669', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 670', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 697', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 715', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 730', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 735', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N 761', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),

-- A series
('N A7', 'Norway', 'Kanslergata, Gamlebyen, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A13', 'Norway', 'Sørbø kirke, Rennesøy', 'Rennesøy', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A53', 'Norway', 'Eik, Sokndal', 'Sokndal', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A71', 'Norway', 'Lom kirke', 'Lom', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A72', 'Norway', 'Lom kirke', 'Lom', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A77', 'Norway', 'Lom kirke', 'Lom', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A118', 'Norway', 'Søndre felt, Gamlebyen, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A215', 'Norway', 'Nordre felt II, Gamlebyen, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A234', 'Norway', 'Storgaten 24/26, Tønsberg', 'Tønsberg', 'Vestfold', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A285', 'Norway', 'Vesle Hjerkinn', 'Hjerkinn', 'Oppland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A318', 'Norway', 'Oslo gate 6, Gamlebyen, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N A322', 'Norway', 'Oslo gate 6, Gamlebyen, Oslo', 'Oslo', 'Oslo', 1000, 1300, 'runic inscription', 'stone', 'official', 'Norwegian corpus', now(), now()),

-- B series (Bryggen Bergen continued)
('N B8', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B9', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B11', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B13', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B22', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B26', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B28', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B29', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B39', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B58', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B66', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B74', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B77', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B94', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B111', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B118', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B122', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B127', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B128', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B136', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B145', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B149', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B172', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B181', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B184', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B189', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B190', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B191', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B192', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B200', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B215', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B218', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B249', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B250', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B252', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B333', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B351', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B361', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B380', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B390', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B416', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B417', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B420', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B424', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B434', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B441', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B448', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B453', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B493', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B557', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B582', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B584', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B605', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B606', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B615', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B644', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B654', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B660', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),
('N B663', 'Norway', 'Bryggen, Bergen', 'Bergen', 'Hordaland', 1100, 1400, 'runic inscription', 'wood', 'official', 'Norwegian corpus', now(), now()),

-- IK series
('N IK24', 'Norway', 'Bjørnerud', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),
('N IK244', 'Norway', 'Fredrikstad', 'Fredrikstad', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian corpus', now(), now()),

-- NIÆR series (Norwegian Archaeological Records)
('NIÆR 1', 'Norway', 'Tune', 'Tune', 'Østfold', 400, 600, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 2', 'Norway', 'Fredrikstad', 'Fredrikstad', 'Østfold', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 3', 'Norway', 'Frøihov', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 9', 'Norway', 'Stenstad', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 19', 'Norway', 'Kjølevik', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 36', 'Norway', 'Bjørnerud', 'Unknown', 'Unknown', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 39', 'Norway', 'Vetteland, Ogna', 'Ogna', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 53', 'Norway', 'Møgedal, Helleland', 'Helleland', 'Rogaland', 1000, 1300, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now()),
('NIÆR 55', 'Norway', 'Eggja, Stedje', 'Stedje', 'Sogn og Fjordane', 700, 800, 'runestone', 'stone', 'official', 'Norwegian Archaeological Records', now(), now())

ON CONFLICT (signum) DO NOTHING;