-- Lägg till DR 360 (Björketorps stenen) - en av Sveriges mest berömda runstenar
INSERT INTO runic_inscriptions (
  signum,
  name, 
  name_en,
  alternative_signum,
  location,
  parish,
  municipality,
  county,
  landscape,
  country,
  coordinates,
  transliteration,
  translation_sv,
  translation_en,
  object_type,
  material,
  style_group,
  period_start,
  period_end,
  dating_text,
  historical_context,
  scholarly_notes,
  raa_number
) VALUES (
  'DR 360',
  'Björketorps stenen',
  'Björketorp Stone', 
  ARRAY['DK Bl6', 'L 2058', 'KJ 97', 'Bl 6'],
  'Björketorp, Listerby socken',
  'Listerby socken',
  'Ronneby',
  'Blekinge län',
  'Blekinge',
  'Sverige',
  POINT(15.3807, 56.2023),
  '§A hᴀidz runo ronu ¶ fᴀlᴀhᴀk hᴀiderᴀ g¶inᴀrunᴀz ᴀrᴀgeu ¶ hᴀerᴀmᴀlᴀusz ¶ utiᴀz welᴀdᴀude ¶ sᴀz þᴀt bᴀrutz §B uþᴀrᴀbᴀ sbᴀ',
  'Jag, runornas mästare, döljer här kraftfulla runor. Ständigt plågad av ondska, dömd till lömsk död är den som bryter detta monument. Jag spår förstörelse.',
  'I, master of the runes(?) conceal here runes of power. Incessantly (plagued by) maleficence, (doomed to) insidious death (is) he who breaks this (monument). I prophesy destruction.',
  'runsten',
  'granit',
  'Rak',
  520,
  700,
  '520-700 e.Kr. (urnordisk tid)',
  'En av Sveriges mest berömda runstenar med en förbannelse mot den som skadar stenen. Från urnordisk tid, mycket äldre än de flesta andra runstenar. Står på sin ursprungliga plats i Björketorp.',
  'Innehåller en av de mest kända förbannelserna i runstenshistorien. Urnordisk inskrift från 500-700-talet. En av tre runstenar som tillsammans kallas "Blekingstenarnas förbannelse".',
  'RAÄ 381'
);