-- Lägg till Karlevistenen (Öl 1) i databasen
INSERT INTO runic_inscriptions (
  signum,
  location,
  parish,
  municipality,
  county,
  province,
  landscape,
  country,
  object_type,
  style_group,
  coordinates,
  transliteration,
  normalization,
  translation_sv,
  translation_en,
  dating_text,
  period_start,
  period_end,
  dating_confidence,
  historical_context,
  scholarly_notes,
  complexity_level,
  uncertainty_level,
  data_source
) VALUES (
  'Öl 1',
  'Karlevi',
  'Vickleby socken',
  'Mörbylånga kommun',
  'Kalmar län',
  'Kalmar län',
  'Öland',
  'Sweden',
  'Runsten',
  'RAK',
  point(16.43983, 56.60751),
  '§A + s-a... --(s)- i(a)s · satr · aiftir · si(b)(a) · kuþa · sun · fultars · in hons ·· liþi · sati · at · u · -ausa-þ-... +: fulkin : likr : hins : fulkþu : flaistr (:)· uisi · þat · maistar · taiþir : tulka · þruþar : traukr : i : þaimsi · huki · munat : raiþ:uiþur : raþa : ruk:starkr · i · tanmarku : --ntils : iarmun··kruntar : urkrontari : lonti
§B {÷ IN| |NONIN- ¶ + HE... ...}',
  '§A S[t]æ[inn] [sa]s[i] es sattr æftiʀ Sibba Goða/Guða, sun Fuldars, en hans liði satti at ... ... Fulginn liggʀ hinns fylgðu, flæstr vissi þat, mæstaʀ dæðiʀ dolga Þruðaʀ draugʀ i þæimsi haugi; munat Ræið-Viðurr raða rogstarkʀ i Danmarku [Æ]ndils iarmungrundaʀ uʀgrandaʀi landi.
§B {In nomin[e](?) Ie[su](?) ...}',
  'Sten denne blev satt efter Sibbe den vise, Foldars son, men hans följe satte vid ön ... En hjälte, vars bana, såsom var man visste, utmärktes genom de största bedrifter, ligger gömd i denna gravhög. En dygdigare, stridsmäktig sjöhjälte ska aldrig komma att råda över land i danska riket.',
  'This stone was set after Sibbe the Good, Foldar''s son, but his retinue set [this memorial] on the island ... A hero lies hidden in this mound, whose deeds, as most men knew, were distinguished by the greatest exploits. A more righteous, battle-strong sea-hero shall never rule over land in the Danish realm.',
  'Slutet av 900-talet',
  950,
  999,
  0.9,
  'Karlevistenen är en av Sveriges mest berömda runstenar med en skaldestrof på dróttkvætt-mått. Stenen restes över hövdingen Sibbe och innehåller både prosa och skaldedikt med flera kenningar.',
  'Innehåller en av få bevarade skaldestrofer på dróttkvætt-versmått tillsammans med Sigtunadosan. Dikten använder kenningar som "stridernas Truds arbetare" för hövding och "Vagn-Vidur" för skeppshövding. Under runinskriften finns en kort medeltida latin-inskrift som möjligen betyder "i Jesu namn".',
  'complex',
  'low',
  'Manual entry'
);